// ui-figma/src/app/components/navigation.tsx
import { Link, useLocation } from "react-router";
import { Video, Menu, X } from "lucide-react";
import { useState } from "react";
import { Button } from "./ui/button";

export function Navigation() {
  const location = useLocation();
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const navLinks = [
    { path: "/", label: "作品展示" },
    { path: "/services", label: "服务" },
    { path: "/consulting", label: "商业咨询" },
    { path: "/about", label: "关于我" },
  ];

  const isActive = (path: string) => location.pathname === path;

  return (
    <nav className="sticky top-0 z-50 bg-white/80 backdrop-blur-lg border-b border-gray-200">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          {/* Logo */}
          <Link to="/" className="flex items-center gap-2 hover:opacity-80 transition-opacity">
            <Video className="w-8 h-8 text-blue-600" />
            <span className="text-xl font-semibold">影像创作者</span>
          </Link>

          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center gap-8">
            {navLinks.map((link) => (
              <Link
                key={link.path}
                to={link.path}
                className={`text-sm transition-colors ${
                  isActive(link.path)
                    ? "text-blue-600 font-medium"
                    : "text-gray-700 hover:text-blue-600"
                }`}
              >
                {link.label}
              </Link>
            ))}
          </div>

          {/* Login Button */}
          <div className="hidden md:block">
            <Link to="/login">
              <Button variant="outline" size="sm">
                登录
              </Button>
            </Link>
          </div>

          {/* Mobile Menu Button */}
          <button
            className="md:hidden p-2"
            onClick={() => setIsMenuOpen(!isMenuOpen)}
          >
            {isMenuOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
          </button>
        </div>
      </div>

      {/* Mobile Menu */}
      {isMenuOpen && (
        <div className="md:hidden border-t border-gray-200 bg-white">
          <div className="px-4 py-4 space-y-3">
            {navLinks.map((link) => (
              <Link
                key={link.path}
                to={link.path}
                className={`block py-2 text-sm ${
                  isActive(link.path)
                    ? "text-blue-600 font-medium"
                    : "text-gray-700"
                }`}
                onClick={() => setIsMenuOpen(false)}
              >
                {link.label}
              </Link>
            ))}
            <Link to="/login" onClick={() => setIsMenuOpen(false)}>
              <Button variant="outline" size="sm" className="w-full">
                登录
              </Button>
            </Link>
          </div>
        </div>
      )}
    </nav>
  );
}

// pbw-web-frontend/src/components/layout/Navigation.vue
<script setup lang="ts">
import { ref } from 'vue'
import { RouterLink, useRoute } from 'vue-router'

const route = useRoute()
const isMobileMenuOpen = ref(false)

const links = [
  { label: '首页', path: '/' },
  { label: '服务课程', path: '/services' },
  { label: '商业咨询', path: '/consulting' },
  { label: '关于我', path: '/about' },
]

function isActive(path: string) {
  return route.path === path
}

function closeMobileMenu() {
  isMobileMenuOpen.value = false
}
</script>

<template>
  <header class="border-b border-gray-100 bg-white">
    <div class="mx-auto flex max-w-7xl items-center justify-between px-6 py-4">
      <RouterLink to="/" class="text-xl font-bold tracking-tight text-gray-950" @click="closeMobileMenu">
        影像创作
      </RouterLink>

      <nav class="hidden items-center gap-8 md:flex" aria-label="主导航">
        <RouterLink
          v-for="link in links"
          :key="link.path"
          :to="link.path"
          :data-nav-path="link.path"
          class="text-sm transition-colors"
          :class="isActive(link.path) ? 'font-semibold text-gray-950' : 'text-gray-500 hover:text-gray-950'"
        >
          {{ link.label }}
        </RouterLink>
        <RouterLink to="/login" class="rounded-lg bg-gray-950 px-4 py-2 text-sm font-medium text-white">
          登录 / 注册
        </RouterLink>
      </nav>

      <button
        data-testid="mobile-menu-toggle"
        type="button"
        class="rounded-lg p-2 text-gray-950 md:hidden"
        aria-label="打开菜单"
        :aria-expanded="isMobileMenuOpen"
        @click="isMobileMenuOpen = !isMobileMenuOpen"
      >
        <span aria-hidden="true">☰</span>
      </button>
    </div>

    <nav v-if="isMobileMenuOpen" data-testid="mobile-menu" class="border-t border-gray-100 px-6 py-4 md:hidden" aria-label="移动端主导航">
      <div class="flex flex-col gap-3">
        <RouterLink
          v-for="link in links"
          :key="link.path"
          :to="link.path"
          :data-testid="`mobile-nav-link-${link.path.slice(1) || 'home'}`"
          class="rounded-lg px-3 py-2 text-sm"
          :class="isActive(link.path) ? 'bg-gray-100 font-semibold text-gray-950' : 'text-gray-600'"
          @click="closeMobileMenu"
        >
          {{ link.label }}
        </RouterLink>
        <RouterLink to="/login" class="rounded-lg bg-gray-950 px-3 py-2 text-center text-sm font-medium text-white" @click="closeMobileMenu">
          登录 / 注册
        </RouterLink>
      </div>
    </nav>
  </header>
</template>
