// pbw-web-frontend/src/components/sections/home/MatrixAccounts.vue
<script setup lang="ts">
import type { MatrixAccountViewModel } from '@/models'
import ResponsiveImage from '@/components/shared/ResponsiveImage.vue'
import SectionHeading from '@/components/shared/SectionHeading.vue'

defineProps<{ accounts: MatrixAccountViewModel[] }>()
</script>

<template>
  <section data-testid="matrix-accounts" class="mx-auto max-w-7xl px-6 py-24 lg:px-8">
    <SectionHeading title="全平台矩阵" description="在你喜欢的平台继续关注我的创作。" />
    <div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
      <a v-for="account in accounts" :key="account.id" data-testid="matrix-card" :href="account.accountUrl || undefined" target="_blank" rel="noreferrer" class="rounded-2xl border border-gray-200 p-6 transition hover:-translate-y-1 hover:border-gray-900 hover:shadow-md">
        <ResponsiveImage :src="account.platformLogo" :alt="account.platformName" fallback-text="平台" class="mb-5 h-10 w-10 rounded-xl object-cover" />
        <h3 class="font-semibold">{{ account.platformName }}</h3><p class="mt-2 text-sm text-gray-600">{{ account.intro }}</p><p class="mt-5 text-sm font-medium text-gray-900">{{ account.followers }} 粉丝 · {{ account.displayName }}</p>
      </a>
    </div>
  </section>
</template>

// ui-figma/src/app/components/matrix-accounts.tsx
import { ExternalLink } from "lucide-react";
import { ImageWithFallback } from "./figma/ImageWithFallback";

const accounts = [
  {
    id: 1,
    platform: "抖音",
    name: "影像创作者",
    followers: "15万",
    url: "https://douyin.com",
    logo: "/logos/douyin.png",
    color: "bg-black",
  },
  {
    id: 2,
    platform: "B站",
    name: "影像创作者",
    followers: "8万",
    url: "https://bilibili.com",
    logo: "/logos/bilibili.png",
    color: "bg-pink-500",
  },
  {
    id: 3,
    platform: "小红书",
    name: "影像创作者",
    followers: "5万",
    url: "https://xiaohongshu.com",
    logo: "/logos/xiaohongshu.png",
    color: "bg-red-500",
  },
  {
    id: 4,
    platform: "视频号",
    name: "影像创作者",
    followers: "3万",
    url: "https://weixin.qq.com",
    logo: "/logos/wechat-video.png",
    color: "bg-green-500",
  },
];

export function MatrixAccounts() {
  return (
    <section className="py-20 px-4 bg-gradient-to-b from-gray-50 to-white">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-4xl font-bold mb-4">关注我的更多平台</h2>
          <p className="text-gray-600">全网同名，持续更新优质内容</p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {accounts.map((account) => (
            <a
              key={account.id}
              href={account.url}
              target="_blank"
              rel="noopener noreferrer"
              className="group bg-white rounded-xl p-6 shadow-md hover:shadow-xl transition-all duration-300 transform hover:-translate-y-2"
            >
              <div className="flex flex-col items-center text-center">
                {/* Logo */}
                <div className={`${account.color} w-20 h-20 rounded-2xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform`}>
                  <ImageWithFallback
                    src={account.logo}
                    alt={account.platform}
                    className="w-12 h-12 rounded-lg object-cover"
                  />
                </div>

                {/* Platform Name */}
                <h3 className="text-xl font-semibold mb-1">{account.platform}</h3>
                <p className="text-gray-600 text-sm mb-3">{account.name}</p>

                {/* Followers */}
                <div className="mb-4">
                  <span className="text-2xl font-bold text-blue-600">{account.followers}</span>
                  <span className="text-sm text-gray-500 ml-1">粉丝</span>
                </div>

                {/* Visit Link */}
                <div className="flex items-center gap-1 text-blue-600 group-hover:text-blue-700 transition-colors">
                  <span className="text-sm">访问主页</span>
                  <ExternalLink className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                </div>
              </div>
            </a>
          ))}
        </div>
      </div>
    </section>
  );
}
